### ISSUE TITLE
Investigar openstreetmap para obtener sucursales de supermercado

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#104]
Openstreet map tiene una API abierta

uno de los "tags" que los usuarios pueden usar es "show=supermarket" 
http://wiki.openstreetmap.org/wiki/Tag:shop%3Dsupermarket

y en argentina hay varios supers marcados: 
http://www.openstreetmap.org/#map=19/-31.43616/-64.19673&layers=N

hay que investigar como consultar, a través de la API y obtener un listado de sucursales de supermercado de Argentina.

**Comment by mgaitan** [comment]
no es obligación utilizar python, pero aqui hay un wrapper python para la API de osm

https://github.com/metaodi/osmapi

**Comment by jazzido** [comment]
Ahí va: http://overpass-turbo.eu/s/2B6

Con esta query a la OSM Overpass API, sale:

```
node
  ["shop"~"supermarket"]
  (area:3600286393);
  out body;
```

`3600286393` es el id del boundary administrativo de Argentina. Con esa query, pedís los nodos dentro de ese área que están tagueados con _shop=supermarket_.

**Comment by jazzido** [comment]
Acá va un JSON que scrapié del primer sitio de INDEC que publicaba precios ("Precios en su sitio" se llamaba?). Tiene muchos supermercados en CABA:

http://jsonblob.com/api/jsonBlob/53079f7fe4b04ce201a45478

**Comment by mgaitan** [comment]
@jazzido 1º muchas gracias! 2º, por qué en el geojson exportado de la consulta me salen menos resultados que los "nodos" que se ven en el mapita de overpass-turbo.eu?

https://gist.github.com/mgaitan/9141275#file-supermarkets-ar-osm-geojson

**Comment by mgaitan** [comment]
ah. parece que mandé fruta y están todos.
y qué fachero que github renderice los geojson!

**Comment by jazzido** [comment]
El visor GeoJSON de Github clusteriza por proximidad, por eso.

**Comment by jazzido** [comment]
ah, je. listo.

**Comment by jazzido** [comment]
Sí, es muy fachero. Y todavía más canchero es que muestra _diffs_ de un GeoJSON!: https://github.com/blog/1772-diffable-more-customizable-maps
