### ISSUE TITLE
Configurar Travis-CI 

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#110]
si bien todavia no hay muchos tests, estamos [intentando cambiar eso](https://github.com/mgaitan/preciosa/search?q=tests&ref=cmdform). 

Para mejorar la calidad y facilitar la integración de codigo de distintos contribuidores, no sólo intentaremos aumentar la cantidad de tests (obligatorios en funcionalidades críticas del sistema) sino que necesitamos probarlos bajo un sistema de integración continua

[Travis-CI](https://travis-ci.org/) es un servicio gratuito para proyectos de software libre. 

Hay que crear el [archivo de configuración](http://docs.travis-ci.com/user/languages/python/) utilizando nuestro requirements.txt y postgres+postgis

https://github.com/mgaitan/preciosa/search?q=tests&ref=cmdform

**Comment by jairot** [comment]
Postgres viene instalado... hace falta setupear postgis, este link puede ser util:

http://mattmakesmaps.com/blog/2014/01/11/configure-postgis-with-travis-ci/

Martin, me parece que el link entre el repo y travis lo tendrias que hacer vos, porque el repo es tuyo.

Saludos, J

**Comment by mgaitan** [comment]
ok, pero alguien que se cope, se arme el archivo de configuracion en su
fork y despues yo uso el mismo desde acá.
