### ISSUE TITLE
Agregar enlace/botón flotante de feedback en sitio web

### ISSUE THREAD

**Issue by luuuciano** [mgaitan/preciosa#116]
Cuando comiencen a llegar los voluntarios (y usuarios) de preciosa estará bueno que puedan reportar cosas raras que encuentren en el sistema.
Si ven un botón/enlace de feedback (cómo traducir eso?) lo tendrán bien a mano y así se recibirán fácilmente los reportes de problemas que existan.

O incluso sugerirán cosas, etc...

**Comment by mgaitan** [comment]
Se puede probar esta app https://github.com/jaredly/django-feedback
