### ISSUE TITLE
[BUG] Odd message al pie en la sección Voluntarios/Agregar logo

### ISSUE THREAD

**Issue by luuuciano** [mgaitan/preciosa#117]
Al pie de la sección "Voluntarios/Agregar logo" aparece un mensaje:
{# esto es un hack porque django-image-cropping necesita si o si ambos fields para funcionar. simplemente oculto dinámicamente el que no corresponda al "paso" #}

?

**Comment by mgaitan** [comment]
fixed in 101e2ed
