### ISSUE TITLE
Registrar al newsletter desde el form de registración

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#125]
a los que se suscriban a Voluntarios se le podrá poner un tilde de "querés suscribirte al newsletter?"? sería un gol

**Comment by diegoduncan21** [comment]
lo que se pide es que al registrarse( o sea acá: /account/signup/) le aparezca un checkbox para subscribirse al newsletter?
si es así, ya lo tengo hecho, si no es asi coméntame un poco mas.

**Comment by mgaitan** [comment]
On Tue, Mar 11, 2014 at 1:36 AM, Diego notifications@github.com wrote:

> si es así, ya lo tengo hecho, si no es asi coméntame un poco mas.

eso mismo.

de paso, tu idea de que además elija la ciudad es buena.
hay que chusmear esto
http://django-user-accounts.readthedocs.org/en/latest/usage.html#customizing-the-sign-up-process

## 

mgaitan.github.io
textosyprextextos.com.ar

**Comment by diegoduncan21** [comment]
así mismo lo hice, entonces lo del newsletter esta hecho, hice una app
"accounts" para poder alojar los archivos forms.py y views.py,
entonces queres que ademas del newsletter pueda elegir la ciudad a la que
pertenece?

2014-03-11 10:02 GMT-03:00 Martín Gaitán notifications@github.com:

> On Tue, Mar 11, 2014 at 1:36 AM, Diego notifications@github.com wrote:
> 
> > si es así, ya lo tengo hecho, si no es asi coméntame un poco mas.
> 
> eso mismo.
> 
> de paso, tu idea de que además elija la ciudad es buena.
> hay que chusmear esto
> 
> http://django-user-accounts.readthedocs.org/en/latest/usage.html#customizing-the-sign-up-process
> 
> ## 
> 
> mgaitan.github.io
> textosyprextextos.com.ar
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/mgaitan/preciosa/issues/125#issuecomment-37292467
> .

## 

_Diego Puente_

**Comment by mgaitan** [comment]
2014-03-11 10:07 GMT-03:00 Diego notifications@github.com:

> entonces queres que ademas del newsletter pueda elegir la ciudad a la que
> pertenece?

si, estaría buenísimo. si además podemos pre-cargar el dato a partir de
"geoip" mucho más mejor

http://pygeoip.readthedocs.org/en/v0.3.1/getting-started.html

PD: pero mandá lo que ya tenés y encaremos lo otro aparte, te parece?

**Comment by diegoduncan21** [comment]
dale, mejor

El 11 de marzo de 2014, 10:30, Martín Gaitán notifications@github.comescribió:

> 2014-03-11 10:07 GMT-03:00 Diego notifications@github.com:
> 
> > entonces queres que ademas del newsletter pueda elegir la ciudad a la
> > que
> > pertenece?
> 
> si, estaría buenísimo. si además podemos pre-cargar el dato a partir de
> "geoip" mucho más mejor
> 
> http://pygeoip.readthedocs.org/en/v0.3.1/getting-started.html
> 
> PD: pero mandá lo que ya tenés y encaremos lo otro aparte, te parece?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/mgaitan/preciosa/issues/125#issuecomment-37294862
> .

## 

_Diego Puente_

**Comment by mgaitan** [comment]
cerrado en #196
