### ISSUE TITLE
[BUG] Django account envia mensajes de confirmación en inglés

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#132]
aun cuando tradujimos los strings en #81 (incluyendo pinax-theme-account ...) los emails que se envian siguen estando en ingles. 

revisar

https://github.com/pinax/pinax-theme-bootstrap-account/tree/master/pinax_theme_bootstrap_account/templates/account/email

**Comment by diegoduncan21** [comment]
perdón, no vi que había una issue, acá lo hice: https://github.com/mgaitan/preciosa/pull/217
