### ISSUE TITLE
Crear un entorno de desarrollo basado en Vagrant

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#134]
En este momento, el desarrollo de preciosa se basa fuertemente en la colaboración voluntaria y esporádica de programadores. Sin embargo, cierta complejidad en la [instalación](https://github.com/mgaitan/preciosa/blob/develop/INSTALL.md) no ayuda, sobre todo en ambientes distintos a Linux Debian/Ubuntu  

Una alternativa es  http://www.vagrantup.com/  que unifica un entorno de desarrollo en una maquina virtual, pero "comunicada" con la maquina host: el desarrollador no trabaja directmanete sobre la maquina virtual sino en su propio entorno, con las herramientas (editor, etc) que utiliza habitualmente, "deployando" su trabajo contra vagrant. 

La tarea es realizar una instacion de preciosa en una base box de vagrant ubuntu 13.10

**Comment by jairot** [comment]
Yo voy a estar trabajando con esta tarea. Si alguien mas la esta realizando que avise! caso contrario continuo yo

**Comment by mgaitan** [comment]
On Sat, Mar 1, 2014 at 12:03 PM, Jairo Trad notifications@github.comwrote:

> Yo voy a estar trabajando con esta tarea. Si alguien mas la esta
> realizando que avise! caso contrario continuo yo

avanti jairo, Mati que se habia ofrecido lo emperdelegué con otra cosa

**Comment by jairot** [comment]
Ya esta, aca pueden ver el Link con las instrucciones en la Wiki:

https://github.com/mgaitan/preciosa/wiki/Instalar-Preciosa-Con-Vagrant

Me gustaría que alguien lo valide para darle el OK.

**Comment by jairot** [comment]
Matias me sugirió una versión alternativa: 
https://gist.githubusercontent.com/matuu/9307326/raw/784918b07153ea3728eeedd656b2fb0eb72c9122/preciosasetup.sh
Esta alternativa tiene un pro y un contra:

PRO: los datos del repo quedan en una carpeta compartida, esto te permite usar y editar los archivos de manera local, y ejecutar el django en la maquina virtual.

CONTRA: yo tengo ubuntu 12.10 y no hay manera de hacerlo andar a eso. Básicamente por la versión de VirtualBox. El Soporte de la solución de Matias, seria a partir de la versión 13.04

Yo creo que mi sistema es viejo... así que me parece que usar la soluciona de matias no es muy descabellada. Habria que actualizar la wiki para aclarar que los archivos estan disponibles para editar de manera local.

**Comment by mgaitan** [comment]
la verdad entiendo poco. Cual es la parte de la versión de Mati que reemplaza o mejora la de Jairo?
estoy funca sin dramas en sistemas host no debian/ubuntu? ejemplo: windows ?

**Comment by mgaitan** [comment]
una cosa que veo, sin probar, es que el setup de la base está asinado al
user "dev"

cuando instalé travis tuve que cambiar el "default" de postgres para usar
el que user "postgres" que pide.
https://github.com/mgaitan/preciosa/blob/develop/preciosa/settings.py#L23

una posibilidad es "overridear" esta config en un local_settings.py o bien
hacer un usuario postgres para la base preciosa.

2014-03-02 14:12 GMT-03:00 Jairo Trad notifications@github.com:

> Matias me sugirió una versión alternativa:
> 
> https://gist.githubusercontent.com/matuu/9307326/raw/784918b07153ea3728eeedd656b2fb0eb72c9122/preciosasetup.sh
> Esta alternativa tiene un pro y un contra:
> 
> PRO: los datos del repo quedan en una carpeta compartida, esto te permite
> usar y editar los archivos de manera local, y ejecutar el django en la
> maquina virtual.
> 
> CONTRA: yo tengo ubuntu 12.10 y no hay manera de hacerlo andar a eso.
> Básicamente por la versión de VirtualBox. El Soporte de la solución de
> Matias, seria a partir de la versión 13.04
> 
> Yo creo que mi sistema es viejo... así que me parece que usar la soluciona
> de matias no es muy descabellada. Habria que actualizar la wiki para
> aclarar que los archivos estan disponibles para editar de manera local.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mgaitan/preciosa/issues/134#issuecomment-36459549
> .

## 

mgaitan.github.io
textosyprextextos.com.ar

**Comment by jairot** [comment]
El Script de Matias pone todos los datos en una carpeta compartida, el mio lo ponia adentro de la VM. 

No funciona, hasta donde yo se en windows, pero si en cualquier sistema *nix... el problema para esto esta en la variable de entorno que apunta al repositorio. No tengo a mano una maquina con Windows para ponerme a probar esto. 

Uhmmm podemos cambiar el script para que use el usuario postgres y no el dev asi es menos lio me parece

**Comment by mgaitan** [comment]
estuve mirando un ejemplo de uso que me parece interesante https://github.com/torchbox/wagtaildemo

no sólo incluye el Vagrantfile y el script de instalacion en el propio repo, sino que en vez de usar un basebox usa una con las dependencias ya instaladas. No podemos armar una box así? yo puedo hostearla si hace falta.  

acá se explica como se usa eso  
http://wagtail.readthedocs.org/en/latest/gettingstarted.html#using-vagrant

**Comment by mgaitan** [comment]
empecé un intento de builder para preciosa

https://github.com/mgaitan/vagrant-preciosa-base

tengo que actualizar virtualbox y vagrant poque tambien estoy usando un ubuntu viejo, pero veré si puedo sacarlo andando

**Comment by jairot** [comment]
Se puede hacer eso Martin. Mirando lo que queres parece bastante simple.

Sobre la Box, con las dependencias instaladas, el tradeoff es que cuando bajas de los servers que recomienda usar vagrant, bajas al palo... mientras que cuando bajas los datos desde un server tuyo no se si se baja tan rápido el box. Esa diferencia de tiempo debería poder cruzarse con el tiempo que tardas en bajar tooodas las dependencias.

Yo lo puedo hacer mañana.... pero si la seguís vos, tomo otro issue

**Comment by jairot** [comment]
#145 ahi esta una primera versíon del install... lo valide con VirtualBox 4.3 y Vagrant desde la version 1.2

**Comment by mgaitan** [comment]
@jairot hice mi intento, aprendí un poco en el camino pero no puedo garantizar que funque bien 

Mi vagrantfile y el script install asociado están en https://github.com/mgaitan/preciosa/tree/134_vagrant

esta basada en una custom box generada con https://github.com/mgaitan/vagrant-preciosa-base 
que incluye todas las dependencias actuales en forma de wheels (o sea, no descarga y ni compila, solo los descomprime) y la base de datos ya creada. 

el problema es que ¡pesa más de 700mb! 

(a priori, yo pensaba que era piola tener una box super customizada para el proyecto. Pero reflexionando un poco, entiendo que vagrant se está usando cada vez más y es más común que los devs tengan una "base box saucy32" ya descargada, y no asi una "preciosa-base.box", por lo que en vez de "ahorrarle" descargas y tiempo de setup mas bien se lo estoy aumentando)

por otro lado... no sé por qué, no pude hacer andar el `vagrant up` de preciosa. Al parecer tengo un problema en el `synced_folder` y se queda clavado en el paso  `./manage.py syncdb --no-input` . Si entro via ssh (`vagrant ssh`) no puedo tirar un ls en la carpeta supuestamente compartida ad hoc `/home/vagrant/preciosa`  ni en la que vagrant comparte automaticamente `/vagrant` 

Así que lamentando haber perdido bastante tiempo (pero contento con lo que aprendí) propongo que si alguien confirma que la versión de @jairot funca, mezclo esa. 

saludos

**Comment by pablocelayes** [comment]
Ahí miro esto y la versión de @jairot y les tiro feedback.
