### ISSUE TITLE
Realizar scrapper de Disco Virtual

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#148]
realizar un management command que  realice scrapping de productos, precios y fotos de 
[Disco Virtual](https://www3.discovirtual.com.ar/Comprar/Home.aspx) 

disco asigna un ID a cada producto, que no coincide con el UPC.  Es el primer parámetro en llamadas a funciones javascript del tipo: 

``` javascript
MArt(405682,'60.55');
```

El algorimto debe cumplir 

1) Revisar si conocemos el ID de disco->Producto via TrackProducto (ref #146)
2) Si el producto es conocido, se creará una instancia de Precio para el producto y la sucursal online "Disco Virtual"
3) Si el producto no es conocido, intentar reconocerlo a traves de la descripción. (ref #80). Si se encuentra un producto con suficiente certeza, crear una instancia de `TrackProducto` que lo registre y luego realizar 2).

4) En cualquer caso que se detecte un producto (via TrackProducto o por inferencia) y este no tuviese un logo, bajar y asignar el de Disco. 

5) Los productos sin PLU conocido y no hallados mendiate inferencia, debe guardarse en un CSV/log

**Comment by mgaitan** [comment]
Esto está realizándolo Hernán

**Comment by hernantz** [comment]
## Pasos a seguir

El sitio utiliza ajax para recargar el listado de productos y es necesario tener una sesion para navegar.

# 

Obtener una session id de: https://www3.discovirtual.com.ar/Login/Invitado.aspx

# 

https://www3.discovirtual.com.ar/Comprar/Menu.aspx?IdLocal=9235&IdTipoCompra=4&Fecha=20140301
Acá están los ids organizados por categorías jerárquicas con su nombre y id.

# 

https://www3.discovirtual.com.ar/ajaxpro/_MasterPages_Home,DiviComprasWeb.ashx?method=MostrarGondola
`{"idMenu":2660}`
Acá se van haciendo las consultas para ver los productos de una categoría, enviándole por post el id de la categoría, pero esta paginado.

# 

https://www3.discovirtual.com.ar/ajaxpro/_MasterPages_Home,DiviComprasWeb.ashx?method=PecActualizar
`{"pecActualizarFuncion":0,
"pecControlUniqueID":"",
"pecTablaOrden":1,
"pecTablaElementoOrden":0,
"pecOpcion":1,
"textoBusqueda":"",
"idMenu":2915,
"idPromo":0,
"idPECListaCompraParametro":0,
"idPedido":0,
"sortDirection":0,
"sortExpresion":0,
"paginacion":20,
"paginaActual":1,
"idMiLista":0,
"visualizarFotosArticulos":true}`

La paginación apunta a esta url. Se puede ir seteando los parámetros de idMenu (id de la categoria), paginacion y paginaActual. Se puede saber el total de productos ya que en la pagina al lado de la paginación dice "41-43 de 43"

# 

Para obtener la imagen mas grande del archivo, se envía por post el id del articulo y el precio (que no hace falta que coincida con el verdadero precio del producto), estos datos se pueden sacar del listado de productos ya que cada producto tiene un link del tipo "JavaScript:MArt(16512,'12.50');" donde 16512 seria el id, y 12.50 seria el precio. 

https://www3.discovirtual.com.ar/Comprar/ArticuloMostrar.aspx
`{"idArticulo":405682, "PVenta":81.28}`
