### ISSUE TITLE
[BUG] No carga mapa en alta de sucursal cuando el form tiene errores

### ISSUE THREAD

**Issue by matuu** [mgaitan/preciosa#151]
Cuando la carga no supera las validaciones, y el sistema te redirige nuevamente al formulario con instance != null, el mapa no se muestra. Hay un error javascript con `OpenLayers: Uncaught ReferenceError: OpenLayers is not defined`

para referencia, se puede reproducir el bug en  http://preciosdeargentina.com.ar/voluntarios/sucursal/  (requiere autenticación)

el widget utilizado es un pointfield de floppyforms Implementado para #130

**Comment by mgaitan** [comment]
Cuando el form no valida e intento ver el codigo fuente, el documento aparece como "expirado", quizas porque django o alguien setea algun header en el response?

tendrá esto que ver como que OpenLayer no se cargue?

![](http://snag.gy/MeNBn.jpg)

**Comment by matuu** [comment]
Pude resolver el problema del mapa cuando el formulario de alta no valida, añadiendo en el template un {{ form.media }}. El tema es que en el documento, estos js ya están añadidos, pero al parecer inaccesibles. No entiendo bien por que. 
Pero bueno, añadiendo los "media" el mapa siempre se muestra, y la dirección se conserva (aunque no la altura, aparece como con más zoom).
Lo otro que podemos hacer es usar siempre la inclusión de los js en los templates que usemos el mapa, y quitarlos del general.

**Comment by matuu** [comment]
Ah, por otro lado, en la doc de floppyforms pide que antes de usarlo se ejecuten los test
<code>python manage.py test floppyforms</code>
En mi entorno no pasaron bien. Error de encode. ¿Alguien más puede confirmar esto? Si a más de uno le fallan, entonces puede que falta configurar algo.

**Comment by mgaitan** [comment]
buenisimo matuu. Mandaste un PR con lo de `{{ form.media }}` ?  Lo del zoom debe ser que toma uno distinto, más alejado, por default. No me molesta pero debe ser facil "forzarlo" si ya existe una direccion en el widget. 

Respecto a floppyforms, si me da muchos errores, muchos de los cuales son por cuestiones de locale: los tests están hecho para esperar mensajes en ingles. 

``` diff
  <ul class="errorlist">
  <li>
- Este campo es obligatorio.
+ This field is required.
  </li>
  </ul><p>
  <la
```

Yo no me preocuparia tanto si lograste que te funcione. 

abrazo

**Comment by mgaitan** [comment]
@matuu 

> Pude resolver el problema del mapa cuando el formulario de alta no valida, añadiendo en el template un {{ form.media }}.

envias un pull request de eso?

**Comment by matuu** [comment]
Si, hoy lo hago. Te parece bien esa solución? Tendría que sacar los link a los js del base.html y utilizar {{ form.media }} en cada template que use el mapa. Ok?

**Comment by mgaitan** [comment]
lo que sea que funcione :)

On Mon, Mar 10, 2014 at 8:17 AM, Matias Varela notifications@github.comwrote:

> Si, hoy lo hago. Te parece bien esa solución? Tendría que sacar los link a
> los js del base.html y utilizar {{ form.media }} en cada template que use
> el mapa. Ok?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mgaitan/preciosa/issues/151#issuecomment-37172279
> .

## 

mgaitan.github.io
textosyprextextos.com.ar
