### ISSUE TITLE
Precios cuidados (carrefour)

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#17]
Obtener un archivo json a partir de este PDF

http://t.co/ZVwkQV307I

A diferencia del listado oficial en http://www.precioscuidados.com/listado-precios-cuidados.pdf el de carrefour tiene códigos de barra. 

se puede usar https://github.com/jazzido/tabula

**Comment by cttn** [comment]
Por si sirve.... Utilizando "pdftotxt" pasé el pdf a texto... Se ve bastante bien.

Subí el txt acá:
https://mega.co.nz/#!gJh3DIwA!Fd0zRgywQQ5D0XKHVxicqwDTVaBrNGZwV2BYrjc3_fA

**Comment by mgaitan** [comment]
buenisimo, eso servirá

**Comment by gabriel-deluca** [comment]
acá va el odt 
https://drive.google.com/file/d/0B3eqzsrKFhwOV3VDem5LU0duX1U/edit?usp=sharing

**Comment by mgaitan** [comment]
@gabriel-deluca ese odt es el pdf de #83 ?

**Comment by gabriel-deluca** [comment]
Sip

**Comment by gabriel-deluca** [comment]
Sirvio???

**Comment by mgaitan** [comment]
gabriel, sí, ya lo pasamos a CSV , todavia tenemos que hacer un pequeño
"importador" porque hay que mapear los textos, por ejemplo de "MARCA" a un
ID univoco en la base de datos.

pero es data que nos sirve.

Pregunta, ¿tenes alguna fuente posible de datos?

On Thu, Feb 20, 2014 at 9:26 PM, gabriel-deluca notifications@github.comwrote:

> Sirvio???
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mgaitan/preciosa/issues/17#issuecomment-35686389
> .

## 

mgaitan.github.io
textosyprextextos.com.ar

**Comment by mgaitan** [comment]
PARA ACLARAR: Este ticket TODAVIA NO SE REALIZO. Por un error se cruzó la conversacion de los datos referidos a #83

**Comment by cttn** [comment]
Mañana lo veo junto con el #83.

**Comment by gabriel-deluca** [comment]
Mmm debería ver si puedo obtener una base de datos de los códigos de 
barra para todos los productos en Argentina.

**Comment by gabriel-deluca** [comment]
oki doki

**Comment by mgaitan** [comment]
Depende de #137

**Comment by mgaitan** [comment]
se cierra por datos deprecados. Ticket relacionado en #235
