### ISSUE TITLE
Search box de arriba izquierda, opciones incrementales, no funciona el Enter

### ISSUE THREAD

**Issue by nwolovick** [mgaitan/preciosa#189]
Cuando introducimos un texto en el search box, aparecen los productos que machean.
Si operamos con el teclado (up, down, enter), no funciona.
Si operamos con mouse si.

**Comment by mgaitan** [comment]
gracias por el reporte @nwolovick

**Comment by nwolovick** [comment]
#189 apareció nuevamente, por lo menos en la versión online que está en http://preciosdeargentina.com.ar/
