### ISSUE TITLE
Autenticación anónima

### ISSUE THREAD

**Issue by devedetti** [mgaitan/preciosa#201]
Se me ocurrió el siguiente circuito para autenticar la API "sin autenticación" tradicional.
1. La API no requiere AUTH para el verbo GET.
2. La API requiere AUTH para el verbo POST.
   2.1 Para hacer un POST primero nos registramos en una URL a definir mediante un simple GET.
   2.2 Dicho GET nos devuelve un Token, HASH o palabra secreta que debemos guardar.
   2.3 Cada POST que hagamos debe ir acompañado de dicho Token.
3. En un modelo guardamos esos Token y un puntaje.
   3.1 Cada objeto generado por POST debe tener un FK contra el Token.
   3.2 Conforme al puntaje del Token, la API acepta el POST, lo posterga (no hace nada e informa que "intente más tarde") o lo rechaza (Si el Token está baneado o tiene un puntaje muy bajo).
4. Un proceso se debe encargar de recorrer los objetos creados por POST sin evaluar y ver cuán lejanos de datos reales están. Conforme a eso se le da un puntaje al Token.

Disculpen el formato, espero se entienda bien :)

**Comment by mgaitan** [comment]
Implementado en 1012c2826d7cb83fd9310f142afc39219751df7d
