### ISSUE TITLE
[BUG] Es posible enviar un precio sin monto desde la app movil

### ISSUE THREAD

**Issue by gilgamezh** [mgaitan/preciosa#215]
Si en la app movil no pones nada cuando te pregunta "¿qué precio vez?" y le das Confirmar deja el producto con precio = 0.
Lo mismo sin ingresas precio = 0

Ejemplo: yerba con palo playadigo 1Kg | 77937040022

**Comment by mgaitan** [comment]
desde el lado del server se fixea con este cambio
https://github.com/mgaitan/preciosa/compare/6eb3611...20f1af9
