### ISSUE TITLE
favicon para el sitio web!

### ISSUE THREAD

**Issue by luuuciano** [mgaitan/preciosa#219]
Y bue, es una boludez... pero quedaría lindo, jeeeeeeeeee

http://iconhandbook.co.uk/reference/examples/favicons/

**Comment by mgaitan** [comment]
armanos el iconito y lo ponemos!

On Fri, Apr 11, 2014 at 11:45 AM, luuuciano notifications@github.comwrote:

> Y bue, es una boludez... pero quedaría lindo, jeeeeeeeeee
> 
> http://iconhandbook.co.uk/reference/examples/favicons/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mgaitan/preciosa/issues/219
> .

## 

mgaitan.github.io
textosyprextextos.com.ar

**Comment by luuuciano** [comment]
A ver, acá va uno!

En realidad es un ICO, cuidado... sacarle el .png y ponerlo a .ico (es que github no le gustan los .ico parece)
Lo que no se es si le hace algún proceso... si no usá el de tu email, je

![favicon ico](https://cloud.githubusercontent.com/assets/6766551/2690474/f60f2f3e-c348-11e3-9775-e7e0013054a5.png)

PD: acabo de compararlos y son iguales... hay que renombrarlo a .ico nomásssssssss

**Comment by mgaitan** [comment]
fixed 27f6cda37e
