### ISSUE TITLE
Marcas Mondelēz International (ex Kraft)

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#22]
armar un listado desde 

http://global.mondelezinternational.com/ar/es/Brands/default.aspx

en los posible incluir logos

**Comment by mgaitan** [comment]
Duzdevich hizo el CSV a mano. 

https://drive.google.com/file/d/0B-9td98rqeZ0RFBUT0hYN0pxRG1KNlE2ZEtnYjRWMlBhNVdN/edit?usp=sharing

**Comment by JuanPabloDuz** [comment]
![don felipe](https://f.cloud.github.com/assets/6620359/2176226/10ab7cf6-95ce-11e3-92e3-baca9cf152ae.jpg)
![vizzolini](https://f.cloud.github.com/assets/6620359/2176227/10afde9a-95ce-11e3-9659-46ac657120d1.jpg)
![canale](https://f.cloud.github.com/assets/6620359/2176228/10de712e-95ce-11e3-8c97-4c748ab75d2a.jpg)
