### ISSUE TITLE
Marcas Arcor

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#23]
generar fixture y conseguir logos

```
    Arcor
    Bon o Bon
    Rocklets
    Cofler
    Butter Toffees
    Nikolo
    Hamlet
    Sapito
    Mr. Pop´s
    Menthoplus
    Poosh
    Blow Up
    Mogul
    Topline 
    BigTime
    Noel
    Águila
    Cabsha
    Saladix
    Cereal Mix
    Arcor Helados
    Criollitas
    Diversión
    Formis
    Tofi
    Prestopronta
    Godet
    Hogareñas
    Alka
    Formis
    Maná
    Ser
    Traviata
    Cindor
    Sonrisas
    Rumba
    Opera
    Rex
    Godet
    Slice
    Menthoplus
    Cremino
    Blanco y Negro
    La Campagnola
    BC
    Nereida
    Salsati
    Poncho Negro
    La Vendimia
    Dulciora
    Arcoa
```

**Comment by JuanPabloDuz** [comment]
Solo tiene un pdf de catalogo, necesito instrucciones de qué hacer.

**Comment by mgaitan** [comment]
se pueden recortar los logos del pdf?

On Sat, Feb 8, 2014 at 8:01 PM, JuanPabloDuz notifications@github.comwrote:

> Solo tiene un pdf de catalogo, necesito instrucciones de qué hacer.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mgaitan/preciosa/issues/23#issuecomment-34559260
> .

## 

mgaitan.github.io
textosyprextextos.com.ar

**Comment by mgaitan** [comment]
0055d5a9
