### ISSUE TITLE
En precios de aplicación mobile mostrar fecha de relHave a question? Let's talk!




 Add IssueMilestones   Show everyone what you're working on with a badge on your readme.  Send Pull Request  No Thanks
Backlog 62
231  








evamiento

### ISSUE THREAD

**Issue by luuuciano** [mgaitan/preciosa#230]
En precios de aplicación mobile mostrar fecha de relevamiento, como ya lo muestra en preciosdeargentina.com.ar

Uno al ver el precio tiene dudas de si será que realmente está más barato o el precio es de 3 meses atrás

**Comment by pablocelayes** [comment]
Lo mudamos a https://github.com/mgaitan/preciosa_mobile/issues/62

**Comment by pablocelayes** [comment]
@mgaitan me parece que no tengo poderes para cerrar este. Me los conferís? ;)
