### ISSUE TITLE
Agregar a Voluntarios Precios cuidados -> códigos EAN

### ISSUE THREAD

**Issue by luuuciano** [mgaitan/preciosa#232]
Qué sería?

Sería un listado de los precios cuidados, según las regiones de precios cuidados (varios listados en realidad o UNO sólo, el que tenga > cantidad de productos e incluya al resto).
Que muestran la información de cada producto (lo que si podemos obtener de los pobres PDF o gráficos disponibles por ahí), descripción - precios.

Donde los voluntarios pueden ver qué productos NO tienen códigos EAN (los que ya tengan podrían aparecer más claro, o tachados)... y así contribuir y salir a buscarlos y matchearlos.

Luego reflejar esto en la parte mobile. Para salir a Cazar los EAN de Precios Cuidados.

**Comment by mgaitan** [comment]
se reemplaza por #235
