### ISSUE TITLE
Api detalle sin sucursal asociada

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#236]
Para la implementación de mgaitan/preciosa_mobile#52 se requiere mostrar una pantalla de "detalle de un producto" con **mejores precios** relativos a una ubicación cualquiera y no a una sucursal en particular. 

Si bien el método de `precios.PrecioManager.mejores()` acepta una sucursal o un punto como parámetros, la vista de la API `producto_detalle`  tiene una url de la forma `r"^sucursales/(?P<pk_sucursal>\d+)/productos/(?P<pk_producto>\d+)` que exige el ID de una sucursal. 
### tarea

Implementar una vista análoga a  `producto_detalle` actual, bajo la url `r"^productos/(?P<pk_producto>\d+)` a la que se le pasan los parámetros `lat` y `lon` de la  ubicacion via query.  Por ejemplo: 

`/api/v1/productos/7783?lat=34.5&lon=45.5`

**Comment by flecox** [comment]
https://github.com/mgaitan/preciosa/commit/c5386990023b81d8e4ad993c2644d4bfb76dd765
