### ISSUE TITLE
Import CSV de precios cuidados

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#238]
Conseguimos un dataset completo en formato CSV. 
https://gist.github.com/mgaitan/8cda99cbe40676cb6e15

hay que importarlo a los modelos correspondientes de la app "acuerdo" y generar un fixture de toda la aplicación. 

close #235

**Comment by flecox** [comment]
Martin vos te encargas de esto? o lo tomo yo.. pero ando con poco tiempo.

**Comment by mgaitan** [comment]
2014-06-11 17:03 GMT-03:00 Gonzalo Almeida notifications@github.com:

> Martin vos te encargas de esto? o lo tomo yo.. pero ando con poco tiempo.

lo hago durante el finde.

## 

mgaitan.github.io
textosypretextos.com.ar http://textosyprextextos.com.ar
