### ISSUE TITLE
Marcas Mastellone Hnos. (La Serenísima)

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#25]
```
    La Serenísima, Danonino, Actimel, Vidacol, Ser, Armonía, Fortuna
```

**Comment by JuanPabloDuz** [comment]
Esta está en flash, buscamos imágenes de cualquier fuente?

**Comment by mgaitan** [comment]
si, da igual la fuente. abrazo

2014-02-08 19:57 GMT-03:00 JuanPabloDuz notifications@github.com:

> Esta está en flash, buscamos imágenes de cualquier fuente?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mgaitan/preciosa/issues/25#issuecomment-34559173
> .

## 

mgaitan.github.io
textosyprextextos.com.ar
