### ISSUE TITLE
Marcas SC Johnson

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#30]
http://www.scjohnson.com.ar/nuestrasMarcas/Pages/home.aspx

**Comment by JuanPabloDuz** [comment]
por ejemplo?

**Comment by JuanPabloDuz** [comment]
off 
![6-off](https://f.cloud.github.com/assets/6620359/2115155/b458639e-9049-11e3-8483-281d494cc078.jpg)??

**Comment by mgaitan** [comment]
más bien así

```
Marca, URL
Off, https://f.cloud.github.com/assets/6620359/2115155/b458639e-9049-11e3-8483-281d494cc078.jpg
otra marca,  https://otra_marca.com/logo.jpg
```

un CSV marca, logo

**Comment by JuanPabloDuz** [comment]
adonde te mando los csv?

**Comment by mgaitan** [comment]
mandame al mail si queres, gaitan@gmail.com

abrazo

On Sat, Feb 8, 2014 at 1:59 PM, JuanPabloDuz notifications@github.comwrote:

> adonde te mando los csv?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mgaitan/preciosa/issues/30#issuecomment-34549017
> .

## 

mgaitan.github.io
textosyprextextos.com.ar

**Comment by mgaitan** [comment]
fix b8aed2a
