### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#49]
Digital ocean. VPS: hay que configurar virtualhost (multiples dominios hospedados). el dominio es preciosdeargentina.com.ar 

Se puede armar un script con https://python-deploy-framework.readthedocs.org/en/latest/

**Comment by vdg0** [comment]
Done. 
Encontré en /var/log/nginx/errors.log lo siguiente:

2014/02/11 14:28:33 [emerg] 8219#0: could not build the server_names_hash, you should increase server_names_hash_bucket_size: 32

**Comment by mgaitan** [comment]
it's working
