### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#55]
![preciosa](https://f.cloud.github.com/assets/2355719/2145646/82ebc2f0-93ab-11e3-91ee-dfc96b553ebd.jpg)

Esta ilustración acompaño el articulo en telam. ya pedimos autorización para usarlo como logo. 

cambiar los circulitos negros debajo del carrito por una tilde y una X  (símbolos icónicos  de correcto / incorrecto)

**Comment by jotaweb** [comment]
algo asi???
![preciosa-isologo](https://f.cloud.github.com/assets/6671064/2159365/c5a4209e-94a3-11e3-83bd-1dea64ce4485.jpg)

**Comment by mgaitan** [comment]
ahi va queriendo! 

de mañoso:
- no sé si los pondria "en color" sino directamente el simbolito negro adentro de rectangulitos o circulos que parezcan botones. Asi no solo acompañaran más la estética simple del diseño si no que funciona más iconicamente, en tamaños chiquitios como el del "avatar de facebook" 
- y al reves: ok  y  no ok. 

el Diseñador de esto ya dio el ok y mandó el original vectorial . está acá

https://drive.google.com/#folders/0B-9td98rqeZ0MjVxMzBFa1lwYU0

**Comment by FrancoLM** [comment]
Hola! Se me ocurren un par de cosas:
- El carrito es muy grueso al lado de los signos peso... podría hacerse más fino el carrito, O sino un solo signo peso, con el mismo grosor del carrito.
- Y si las ruedas del carrito son los botones? A la izquierda el OK, derecha el Cancel.

Estoy editando el svg, así que apenas llegue a algún lugar con eso subo una muestra (no me doy mucha maña con eso, jeje).

**Comment by estebandres** [comment]
Una propuesta para el icono (puede usarse en otras partes de la GUI también), lo hice con Inkscape 0.48.3.1.
![logos](https://f.cloud.github.com/assets/4691254/2176703/19f7a63c-95dc-11e3-9569-13749f296c0c.png)
El .svg en:
https://www.dropbox.com/s/pnqy22mkhewumqm/logo_preciosa_final.svg

**Comment by mgaitan** [comment]
Andrés, gracias por la propuesta pero el logo va a tener que basarse en el que ya tenemos, porque de alguna manera la gran exposicion que tuvimos lo convirtió en la "marca", el "icono de preciosa".  Por eso propuse solo ese cambicito sencillo. 

Podés hacer el cambio, mas o menos con lo que pedí a Juan? 

Queres ayudar en una mockup de la app mobile?

**Comment by mgaitan** [comment]
Acá estan los logos

https://drive.google.com/folderview?id=0B-9td98rqeZ0YTFwb0M4ZkpyR2c&usp=sharing

detalle: ¿convendrá que la X y el Thick estén invertidos en posicón ? digo, lo posito primero... :+1:

**Comment by mgaitan** [comment]
logo actualizado. 
https://drive.google.com/folderview?id=0B-9td98rqeZ0YTFwb0M4ZkpyR2c&usp=sharing
