### ISSUE TITLE
form para cargar cadenas/sucursales de super 

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#59]
form para cargar cadenas/sucursales de super  que convenga directamente cargar a mano y no hacer un scrapper.

**Comment by mgaitan** [comment]
for the record, de la lista

> claramente está poco claro (cuac!), pero la idea es algo análogo a la >vista de "marcas", pero para sucursales. O sea, permitir que los usuarios carguen nuevos supermercados.
> 
> podés arrancar con lo básico y despues, si te animás, empezar a hacer >algunas validaciones via Geodjango (que no acepte una sucursal si ya tenemos otra demasiado cerca del punto) y, si ya estamos muy picantes>, meterle google maps para para que el usuario precise la ubicacion en >el mapa.
> 
> https://github.com/madisona/django-google-maps
> 
> otra cosa, se me acaba de ocurrir, es pedirle al usuario que defina (via la pagina de configuracion de perfil o cuando se registra) su >ciudad, de manera que sea el default a la hora de "cargar una nuev>a sucursal".
> 
> Por otro lado también sirve para el "feed", analogo al de marcas, que >aparece a la derecha, que le muestra al usuario cargas de otros usuarios y puede decir "parece correcto" o "parece incorrecto", cosa de poner tener una metrica de aquellas que son sospechosas. Teniendo definida la ciudad de un usuario, podemos mostrarle sucursales recientemente cargadas para dentro/cerca de esa ciudad.
> 
> espero no abrumarte y repito, empezá por lo básico.
> 
> abrazo

**Comment by matuu** [comment]
El 21/02/14 18:26, Martín Gaitán escribió:

> for the record, de la lista
> 
> ```
> claramente está poco claro (cuac!), pero la idea es algo análogo a
> la >vista de "marcas", pero para sucursales. O sea, permitir que
> los usuarios carguen nuevos supermercados.
> 
> podés arrancar con lo básico y despues, si te animás, empezar a
> hacer >algunas validaciones via Geodjango (que no acepte una
> sucursal si ya tenemos otra demasiado cerca del punto) y, si ya
> estamos muy picantes>, meterle google maps para para que el
> usuario precise la ubicacion en >el mapa.
> 
> https://github.com/madisona/django-google-maps
> 
> otra cosa, se me acaba de ocurrir, es pedirle al usuario que
> defina (via la pagina de configuracion de perfil o cuando se
> registra) su >ciudad, de manera que sea el default a la hora de
> "cargar una nuev>a sucursal".
> 
> Por otro lado también sirve para el "feed", analogo al de marcas,
> que >aparece a la derecha, que le muestra al usuario cargas de
> otros usuarios y puede decir "parece correcto" o "parece
> incorrecto", cosa de poner tener una metrica de aquellas que son
> sospechosas. Teniendo definida la ciudad de un usuario, podemos
> mostrarle sucursales recientemente cargadas para dentro/cerca de
> esa ciudad.
> 
> espero no abrumarte y repito, empezá por lo básico.
> 
> abrazo
> ```
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mgaitan/preciosa/issues/59#issuecomment-35775349.
> 
> Dale, arranco con esto. Bien por lo básico!
> Lo de la ciudad del usuario es una muy buena idea, creo que le ahorraría
> tiempo al cargar.
> Cualquier cosa voy consultando por acá.
> Abrazo!

## 

_Matías E. Varela_
Cel.: 260-4290769
Skype: matu.varela
Jadder: matuu@python.org.ar

**Comment by matuu** [comment]
Abrí 3 nuevos issues para lo conversado arriba:
#129: validación via geodjango
#130: google maps en el form
#131: ciudad predeterminada por el usuario
