### ISSUE TITLE
/media no funciona

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#60]
No se ven los thumbnails de los productos

en la página http://preciosdeargentina.com.ar/ me parece que está mal configurada la /media. capaz falte una regla url.
Preciosa - Precios de Argentina |
preciosdeargentina.com.ar

**Comment by aenima-x** [comment]
No es un problema de /media, estas poniendo el path local en el src (src="/home/tin/lab/preciosa/preciosa/site_media/media/productos/0779027200550.jpg")

**Comment by mgaitan** [comment]
faltaba una configuración en nginx, ahora la imagenes en site_media están funcionando

http://preciosdeargentina.com.ar/350-fernet/1608-lata-fernet-branca-750cc

no así las imágenes achicadas (listados)

**Comment by vdg0** [comment]
En los listados, cada imagen resulta:

<img alt="" src=""></div>

**Comment by mgaitan** [comment]
Eso es justamente lo descripto en el ticket #68  Mariano. 
localmente anda bien.
