### ISSUE TITLE
Falla de requerimientos en pip install

### ISSUE THREAD

**Issue by jmesquita** [mgaitan/preciosa#62]
radpress requerido ya no está más publicado y por ende pip no es capaz de instalar todos los paquetes correctamente. Probaré usando otra versión pero como podés ver, 0.4.2 ni figura como disponible. Me pregunto si algo más se va a romper usando 0.4 o si es un alias para la versión más reciente...

```
Downloading/unpacking radpress==0.4.2 (from -r requirements.txt (line 52))
  Could not find a version that satisfies the requirement radpress==0.4.2 (from -r requirements.txt (line 52)) (from versions: 0.1.1, 0.1.10, 0.1.10, 0.1.11, 0.1.11, 0.1.2, 0.1.2, 0.1.3, 0.1.3, 0.1.4, 0.1.4, 0.1.5, 0.1.5, 0.1.5alpha, 0.1.5alpha, 0.1.5beta, 0.1.5beta, 0.1.6, 0.1.6, 0.1.7, 0.1.7, 0.1.8, 0.1.8, 0.1.9, 0.1.9, 0.2.1, 0.2.1, 0.2.3, 0.2.3, 0.2.4, 0.2.4, 0.2, 0.2, 0.3.1, 0.3.1, 0.3.2, 0.3.2, 0.3.3, 0.3.3, 0.3.4, 0.3.5, 0.3, 0.3, 0.3alpha, 0.3alpha, 0.3beta, 0.3beta, 0.4.1, 0.4)
Cleaning up...
No distributions matching the version for radpress==0.4.2 (from -r requirements.txt (line 52))
```

**Comment by mgaitan** [comment]
el problema es que instalé directamente desde el repositorio de desarrollo 

```
$ pip install https://github.com/gkmngrgn/radpress/archive/develop.zip
```

Usá eso por ahora como workaround y fijate si zafas. 

Luego harcodearemos la version correcta y accesible desde pypi en el requirement.txt 

(Como el requirements.txt lo estoy generando via `pip freeze` no quise editarlo a mano para poner la url)

**Comment by jmesquita** [comment]
Ok, veo muchisimos requirements como pyzmq que no tienen nada que ver con Django. Se usa eso en el codigo?

Empiezo a mirar ahora y no quiero matarte a preguntas, pero una cosa que seria bueno hacer para lograr más contribuciones es un guia facil de instalacion del repo. A mi me esta costando un poco, quizás por no saber Django (aún). Esperaba ver un setup.py o algo parecido pero veo que Django tiene su forma especial. Puedo contribuir con eso ni bien lo saque andando pero por ahí te aturdo con algunas preguntitas.

**Comment by jmesquita** [comment]
@mgaitan paso esa discusión a la lista porque no es un bug necesariamente.
