### ISSUE TITLE
radpress==0.4.2 en requirements.txt

### ISSUE THREAD

**Issue by lecerd** [mgaitan/preciosa#67]
Muchachos recién quise instalar el proyecto (dicho sea de paso, mierda que le dieron al $ pip freeze) y me tiró un error de dependencia con radpress==0.4.2.

Ahora le saqué la version y estoy viendo si instala...

A alguno le pasó lo mismo?

**Comment by pandres** [comment]
Yo lo cambie por radpress==0.4 , sucio y rapido por ahora.

2014-02-13 18:27 GMT-03:00 lecerd notifications@github.com:

**Comment by lecerd** [comment]
Buenisimo, la version más nueva es la 0.4.1 según pip pero dejemoslo ahi por las dudas.

**Comment by mgaitan** [comment]
si, dejen el que esté en pypi,. 

el tema es que lo instalé desde el repo github, estaba experimentando cual app plugable usar y quedó ese. supongo que no habrá mucho cambio entre 0.4.1 y 0.4.2
