### ISSUE TITLE
Importar acuerdo de Precios

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#7]
La información de acuerdo de precios (~500 productos por cadena) fue sistematizada en un formato de texto plano tabular por Ezequiel Fernandez Vera a partir de los PDF difundidos por el gobierno. 

Realizamos un [script](https://github.com/mgaitan/preciosa/blob/develop/tools/importador_acuerdo_de_precios.py) que parsea estos datos. 

Hay que extender ese script para incoporar los datos directamente a la base de datos y. de ser posible, incoporar los códigos UPC de los productos referidos cruzando datos con otra fuente de información (quizas los datos de #6 sirvan, al menos para el caso del acuerdo con Walmart). 

En el [repositorio de datos](https://drive.google.com/folderview?id=0B-9td98rqeZ0MjVxMzBFa1lwYU0&usp=sharing) se encuentra disponible el archivo `acuerdo_de_precios.tar.gz` que contiene los archivos aportados por Ezequiel y el json generado hasta el momento

**Comment by zikofv** [comment]
Creo que se podría implementar un script que genere un fixture.
Dentro de "precios.json", para cada producto, tenemos los siguientes campos:
- cadena
- categoría
- contenido
- precio_sur
- marca
- unidad_medida
- precio_norte
- descripción
- id (Este campo no sirve de mucho, es el id que tenían los productos dentro de cada archivo pdf.)

Los campos descripción, contenido y unidad_medida, se mapean directamente a la clase Producto.

En principio, habría que definir la jerarquía de categorías. Para cada cadena las categorías cambian bastante. Por ejemplo, para una cadena, un té puede estar en la categoría "Infusiones", mientras que para otra cadena tiene la categoría "Té Saborizado".
En total hay 177 categorías: https://gist.github.com/zikofv/5770470

Queda analizar como se mapean los campos:
- cadena
- precio_sur
- marca
- precio_norte

**Comment by mgaitan** [comment]
@zikofv si bien es cierto que es bueno que los productos estén bien categorizados, el "grano fino" de clasificación lo podemos ir ajustando a futuro, cuando tengamos una base de productos más amplia. 

A priori yo intentaría importar el árbol de categorías de walmart (#6) y armar un diccionario usando como claves el listado que vos hiciste y como valor la categoria de nivel 3 o 2 importada que más se ajuste.

**Comment by mgaitan** [comment]
este acuerdo de precios quedó desactualizado
