### ISSUE TITLE
Agregar métodos is_published/set_published a Categoria

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#76]
Por recomendación de Tabo (autor de django-treebeard), agregar un field booleano
`is_published` a las categorias para evitar el hack de "ocultar del menu"

un metodo `set_published(bool)`  cambia el status de la categoria y su descendencia

**Comment by tabo** [comment]
La recomendación es básicamente para evitar double takes al hacer revisión y/o colaboración en el código. No es claro por qué el campo `path` es relevante en el estado de la publicación y categorización.

Un primer paso en refactoring sería hacer que el conocimiento de `path` sea solo dentro de `Categoria` y que los clientes de `Categoria` accedan únicamente a métodos expresivos.
