### ISSUE TITLE
Redirección a página de voluntarios luego de confirmación/login exitoso

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/preciosa#84]
```
Natalia:  No está muy fácil de encontrar
Cuando hago clic en el link del mail y confirmo mi mail me manda a la página principal de Preciosa
 me:  ok, voy a revisar eso
```

**Comment by diegoduncan21** [comment]
Esta hecho esto se me hace. Cuando me logueo exitosamente, me lleva a esta url: http://localhost:8000/voluntarios/

**Comment by mgaitan** [comment]
@diegoduncan21 tenés razón. fue en 0edf0260 gracias! ¡acabás de cerrar tu primer ticket! :smile:

**Comment by diegoduncan21** [comment]
great, muy vago para ser el primero, prometo seguir con algo mas jugoso jaja

**Comment by mgaitan** [comment]
la gente de pie: aplausos :clap:
