### ISSUE TITLE
Activar virtualenv en Windows

### ISSUE THREAD

**Issue by ajlopez** [mgaitan/preciosa#89]
Un detalle menor, pero en Windows, para activar el virtualenv de preciosa_ve, se ejecuta desde la linea de comando:

preciosa_ve\Scripts\activate

en lugar de

source preciosa_ve/bin/activate

Para los nuevos en Python, como yo, tal vez habria que aclarar que la creacion del entorno virtualenv preciosa_ve NO HACE FALTA ejecutarla desde el root del repo

**Comment by mgaitan** [comment]
@ajlopez podrás comentar esto en el INSTALL.md  ? tu primer PR :D

**Comment by mgaitan** [comment]
Fixed  in   3d39afd

**Comment by iamjonathanpumares** [comment]
@ajlopez fijate que a mi en la carpeta de Scripts sólo me aparece python.exe, python2.7.exe y pythonw.exe y no se como activar el entorno virtual, podrías ayudarme???

**Comment by ajlopez** [comment]
A mi, en Scripts, me aparece tambien activate.bat y deactivate.bat Son los que hay que usar para activar y desactivar el VirtualEnv en tu linea de comando
